### ISSUE TITLE
Behavioral_Term_Association.csv

### ISSUE THREAD

**Issue by ghost** [zhang587/document-classification#2]
would it be possible to commit the dataset please - I can't run the notebook or the classifier without the data and can't find it easily online.

**Comment by zhang587** [comment]
Just uploaded the csv file. Sorry I only found the dataset that I used for the HCC Classifier.ipynb. The data I used for classifier.py back then was an older version -- I couldn't find it on my computer.

**Comment by ghost** [comment]
Thanks, obviously also please remember not to upload any data you don't have the right to upload. If it's a public dataset then that's all good, but maybe worth checking just to be safe.

**Comment by zhang587** [comment]
For sure. I remember it was from my supervisor back then, I don't know
where/how this dataset was collected, but I wasn't alerted about whether
it's public or not, so I guess it should be fine.
Daren Race <notifications@github.com> 于2018年10月29日周一 上午11:52写道：

**Comment by ghost** [comment]
Agree, I looked at the data too and it appears to be more reference than tied to people so no problems that I see.
